// Centralized styles for the CourseDetail page
// extracted from CourseDetail.jsx to keep the component file cleaner.

const styles = {
  container: {
    width: '100%',
    minHeight: '100vh',
    backgroundColor: '#fff',
    fontFamily: "'Public Sans', sans-serif",
  },
  
  // Hero Section
  hero: {
    width: '100%',
    height: 336,
    background: 'linear-gradient(90deg, #0183ab 4.327%, #14627a 100%)',
    position: 'relative',
  },
  heroContent: {
    maxWidth: 1320,
    height: '100%',
    margin: '0 auto',
    padding: '0 60px',
    position: 'relative',
  },
  breadcrumb: {
    position: 'absolute',
    top: 39,
    left: 106,
    color: '#fff',
    fontSize: 14,
    lineHeight: '22px',
    fontWeight: 400,
  },
  bestSellerBadge: {
    position: 'absolute',
    top: 120,
    left: 46,
    backgroundColor: '#d1e5ce',
    borderRadius: 20,
    padding: '8px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    height: 40,
  },
  badgeIcon: {
    width: 24,
    height: 24,
  },
  starIcon: {
    width: '100%',
    height: '100%',
  },
  badgeText: {
    color: '#3a4b3a',
    fontSize: 12,
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: '0.5px',
    fontFamily: "'Roboto', sans-serif",
  },
  heroTitle: {
    position: 'absolute',
    top: 39,
    left: 200,
    color: '#fff',
    fontSize: 56,
    fontWeight: 600,
    lineHeight: '72px',
    margin: 0,
  },
  heroSubtitle: {
    position: 'absolute',
    top: 120,
    left: 46,
    color: '#fff',
    fontSize: 20,
    fontWeight: 400,
    lineHeight: '28px',
    margin: 0,
    width: 753,
  },
  heroMeta: {
    position: 'absolute',
    top: 251,
    left: 46,
    display: 'flex',
    gap: 11,
  },
  metaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
  },
  metaIcon: {
    width: 20,
    height: 20,
  },
  metaText: {
    color: '#9fc3ce',
    fontSize: 16,
    lineHeight: '24px',
    fontWeight: 400,
  },
  createdBy: {
    position: 'absolute',
    top: 221,
    left: 46,
    fontSize: 16,
    lineHeight: '24px',
    fontWeight: 400,
  },
  createdByLabel: {
    color: '#fff',
  },
  createdByName: {
    color: '#9fc3ce',
    textDecoration: 'underline',
    marginLeft: 5,
  },
  
  // Main Content
  main: {
    maxWidth: 1320,
    margin: '0 auto',
    padding: '0 60px',
    display: 'flex',
    gap: 40,
    position: 'relative',
    paddingTop: 40,
  },
  mainContent: {
    flex: 2,
    maxWidth: 800,
  },
  
  // Rating Card - PIXEL PERFECT
  ratingCard: {
    width: 751,
    height: 102,
    backgroundColor: '#fff',
    borderRadius: 20,
    boxShadow: '2px 4px 12.7px 0px rgba(0,0,0,0.25)',
    display: 'flex',
    marginBottom: 40,
    marginTop: -42,
    position: 'relative',
    zIndex: 10,
  },
  verifiedBadge: {
    width: 99,
    backgroundColor: '#2e7e96',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderRight: '1px solid #bcbcbc',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    position: 'relative',
  },
  verifiedIcon: {
    position: 'absolute',
    top: 12,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 20,
    height: 20,
  },
  verifiedText: {
    color: '#fff',
    fontSize: 14,
    lineHeight: '22px',
    fontWeight: 400,
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  ratingSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRight: '1px solid #bcbcbc',
    padding: '0 20px',
  },
  ratingScore: {
    fontSize: 24,
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '0.048px',
    color: '#000',
  },
  stars: {
    display: 'flex',
    gap: 4,
    height: 17.25,
  },
  starFull: {
    width: 18,
    height: 17.25,
  },
  starHalfContainer: {
    position: 'relative',
    width: 18,
    height: 17.25,
    overflow: 'hidden',
  },
  starBackground: {
    width: 18,
    height: 17.25,
    position: 'absolute',
  },
  starEmpty: {
    width: 18,
    height: 17.25,
  },
  ratingCount: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#889099',
  },
  learnersSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '0 20px',
  },
  usersIcon: {
    width: 30,
    height: 30,
  },
  learnersCount: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: 'rgba(0,0,0,0.75)',
  },
  learnersLabel: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#889099',
  },
  
  // Learn Box
  learnBox: {
    width: 751,
    minHeight: 185,
    border: '1px solid rgba(0,0,0,0.31)',
    borderRadius: 15,
    padding: '8px 20px',
    marginTop: 40,
    marginBottom: 30,
  },
  learnTitle: {
    fontSize: 20,
    fontWeight: 500,
    lineHeight: '28px',
    color: '#000',
    marginBottom: 15,
  },
  learnGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
  },
  learnItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  checkIcon: {
    width: 16.971,
    height: 12.021,
    flexShrink: 0,
  },
  learnText: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '22px',
    color: '#a0a6ad',
  },
  
  // Sections
  exploreSection: {
    padding: '10px 13px',
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 600,
    lineHeight: '28px',
    color: '#000',
    marginBottom: 5,
  },
  topicTags: {
    display: 'flex',
    gap: 10,
  },
  topicTag: {
    width: 100,
    height: 25,
    border: '1px solid rgba(0,0,0,0.32)',
    borderRadius: 7,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#889099',
  },
  
  courseDetailsSection: {
    padding: '0 13px',
    marginBottom: 30,
  },
  detailsGrid: {
    display: 'flex',
    gap: 5,
  },
  detailColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    height: 24,
    width: 313,
  },
  detailIcon: {
    width: 22,
    height: 22,
    flexShrink: 0,
  },
  detailText: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '24px',
    color: '#889099',
    textTransform: 'uppercase',
    width: 287,
  },
  
  contentSection: {
    padding: '10px 13px',
    marginBottom: 30,
  },
  contentDetails: {
    display: 'flex',
    gap: 10,
    marginBottom: 10,
  },
  contentTag: {
    height: 25,
    border: '1px solid rgba(0,0,0,0.32)',
    borderRadius: 7,
    padding: '0 15px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#889099',
  },
  contentList: {
    display: 'flex',
    flexDirection: 'column',
    paddingTop: 8,
  },
  contentItem: {
    backgroundColor: 'rgba(217,217,217,0.5)',
    border: '0.5px solid rgba(0,0,0,0.38)',
    height: 35,
    display: 'flex',
    alignItems: 'center',
    padding: '0 6px',
    gap: 10,
  },
  arrowIcon: {
    width: 24,
    height: 24,
  },
  contentTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#000',
  },
  contentMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
  },
  contentMetaText: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '22px',
    color: '#889099',
  },
  contentDot: {
    width: 4,
    height: 4,
    borderRadius: '50%',
    backgroundColor: '#889099',
  },
  
  requirementsSection: {
    padding: '10px 13px',
    marginBottom: 30,
  },
  requirementsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  requirementItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
  },
  requirementDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: '#889099',
    flexShrink: 0,
  },
  requirementText: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '22px',
    color: '#889099',
  },
  
  descriptionSection: {
    padding: '0 13px',
    marginBottom: 30,
  },
  descriptionText: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: '24px',
    color: '#889099',
  },
  link: {
    color: '#889099',
    cursor: 'pointer',
  },
  
  instructorsSection: {
    padding: '0 13px',
    marginBottom: 30,
  },
  instructorName: {
    fontSize: 18,
    fontWeight: 700,
    lineHeight: '28px',
    color: '#2e7e96',
    textDecoration: 'underline',
    display: 'block',
    marginBottom: 10,
  },
  instructorCard: {
    display: 'flex',
    gap: 25,
    padding: '8px 0',
    marginBottom: 10,
  },
  instructorImage: {
    width: 125,
    height: 125,
    objectFit: 'cover',
    flexShrink: 0,
  },
  instructorDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 7,
  },
  instructorStat: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
  },
  instructorIcon: {
    width: 21,
    height: 21,
    flexShrink: 0,
  },
  instructorStatText: {
    fontSize: 14,
    fontWeight: 400,
    lineHeight: '22px',
    color: '#889099',
  },
  instructorBio: {
    fontSize: 14,
    fontWeight: 400,
    lineHeight: '22px',
    color: '#889099',
  },
  
  // Reviews Section
  reviewsSection: {
    marginTop: 60,
    marginBottom: 40,
  },
  reviewsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    height: 57,
    marginBottom: 10,
  },
  reviewStarIcon: {
    width: 35,
    height: 35,
  },
  reviewsTitle: {
    fontSize: 20,
    fontWeight: 600,
    lineHeight: '28px',
    color: '#000',
  },
  reviewsDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: '#889099',
  },
  reviewsCount: {
    fontSize: 20,
    fontWeight: 600,
    lineHeight: '28px',
    color: '#000',
  },
  reviewsGrid: {
    display: 'flex',
    gap: 20,
  },
  reviewColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  reviewCard: {
    backgroundColor: '#fff',
    border: '0.5px solid #3686f7',
    borderRadius: 16,
    padding: 24,
    boxShadow: '0px 43px 12px 0px rgba(0,0,0,0), 0px 28px 11px 0px rgba(0,0,0,0.01), 0px 16px 9px 0px rgba(0,0,0,0.05), 0px 7px 7px 0px rgba(0,0,0,0.09), 0px 2px 4px 0px rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  reviewUser: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
  },
  reviewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 40,
    backgroundColor: '#01579b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: '20px',
    fontFamily: "'Inter', sans-serif",
  },
  reviewUserInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  reviewUserName: {
    fontSize: 16,
    fontWeight: 600,
    lineHeight: '20px',
    color: '#1a1a1a',
    fontFamily: "'Inter', sans-serif",
  },
  reviewDate: {
    fontSize: 12,
    fontWeight: 400,
    lineHeight: '15px',
    color: 'rgba(0,0,0,0.5)',
    fontFamily: "'Inter', sans-serif",
  },
  reviewStars: {
    height: 24,
    width: 136,
  },
  reviewStar: {
    width: '20%',
    height: 24,
  },
  reviewText: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: '20px',
    color: '#333a4b',
    fontFamily: "'Inter', sans-serif",
  },
  
  // Sidebar - Info Card - PIXEL PERFECT
  sidebar: {
  flex: 1, // Takes up 1/3 of space
  position: 'relative',
},
  infoCard: {
  position: 'sticky',
  top: '20px',
  marginTop: '-200px', // Pulls it into the hero section
  zIndex: 100,
  backgroundColor: '#fff',
  borderRadius: '12px',
  boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
},
  courseImage: {
    width: '100%',
    aspectRatio: '1920/1080',
    objectFit: 'cover',
    borderRadius: 8,
  },
  priceCard: {
    height: 62,
    border: '1px solid rgba(116,116,116,0.24)',
    borderRadius: 15,
    boxShadow: '2px 4px 12.7px 0px rgba(0,0,0,0.25)',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 12px',
  },
  priceInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'absolute',
    left: 40,
    top: '50%',
    transform: 'translateY(-50%)',
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '0.048px',
    color: '#000',
  },
  priceLabel: {
    fontSize: 14,
    fontWeight: 400,
    lineHeight: '22px',
    color: '#889099',
  },
  buyNowBtn: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: 'translateY(-50%)',
    width: 124,
    height: 39,
    backgroundColor: '#14627a',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '24px',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    paddingTop: 13,
  },
  infoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    minHeight: 24,
    width: 313,
  },
  infoIcon: {
    width: 24,
    height: 24,
    flexShrink: 0,
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '24px',
    color: '#889099',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  infoTextMultiline: {
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '24px',
    color: '#889099',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  layoutWrapper: {
  maxWidth: 1200,
  margin: '0 auto',
  display: 'flex',
  gap: '40px',
  padding: '0 20px',
  position: 'relative',
},
contentHeader: {
  display: 'flex',
  alignItems: 'center',
  padding: '15px',
  backgroundColor: '#f8f9fa',
  border: '1px solid #ddd',
  cursor: 'pointer',
  gap: '10px',
}
  
};
export default styles;
